[audio]
buffer_size = 128
device_type = 0
sample_rate = 44100

[gamepad_1p]
left_don = [ 16 ]
left_kat = [ 10 ]
right_don = [ 17 ]
right_kat = [ 12 ]

[gamepad_2p]
left_don = []
left_kat = []
right_don = []
right_kat = []

[general]
audio_offset = 0
fake_online = false
fps_counter = false
judge_counter = false
language = 'en'
log_level = "info"
nijiiro_notes = false
player_1_id = 1
player_2_id = 2
practice_mode_bar_delay = 1
score_method = 'shinuchi'
song_limit = 0
song_timer = false
timer_frozen = true
touch_input = false
visual_offset = 0
webcam_number = -1

[keys]
back_key = 'escape'
borderless_key = 'f10'
exit_key = 'Q'
fullscreen_key = 'f11'
pause_key = 'space'
restart_key = 'f1'

[keys_1p]
left_don = [ 'F' ]
left_kat = [ 'D' ]
right_don = [ 'J' ]
right_kat = [ 'K' ]

[keys_2p]
left_don = [ 'X' ]
left_kat = [ 'Z' ]
right_don = [ 'C' ]
right_kat = [ 'V' ]

[paths]
skin = 'PyTaikoGreen'
tja_path = [ 'Songs' ]

[video]
borderless = false
fullscreen = false
target_fps = -1
vsync = false

[volume]
attract_mode = 1.0
hitsound = 1.0
music = 0.80000001192092896
sound = 1.0
voice = 1.0
